### ISSUE TITLE
CanadaC19 - Initial Package Work Effort 

### ISSUE THREAD

**Issue by debusklaneml** [Covid19R/covid19R#4]
*Package name:* **CanadaC19**
*Dataset names:* cases; mortality; cum_recovered; cum_testing
*Package github repo:* https://github.com/debusklaneml/CanadaC19
*Data source URL:* https://github.com/ishaberry/Covid19Canada
*Description of data set(s):* This data is being scraped from an existing compilation in Canada. All data is compiled through existing publicly available data sources.

Acknowledgements can be found here, but otherwise reference this citation:
Berry I, Soucy J-PR, Tuite A, Fisman D. Open access epidemiologic data and an interactive dashboard to monitor the COVID-19 outbreak in Canada. CMAJ. 2020 Apr 14;192(15):E420. doi: https://doi.org/10.1503/cmaj.75262

- [x] For each dataset, has a `refresh_PKGNAME_*()`function. The _* at the end are for if your package returns multiple datasets.
- [x] Package has a `get_info_PKGNAME()` function.
- [x] Datasets meet the tidy data standard laid out in https://github.com/Covid19R/documentation
- [x] Information returned by `get_info_PKGNAME()` function meets the standards laid out in https://github.com/Covid19R/documentation

**Comment by jebyrnes** [comment]
Fantastic! Let us know if we can help at all!

**Comment by debusklaneml** [comment]
This package has been submitted to CRAN and is ready to be migrated.
