### ISSUE TITLE
Set a cron job

### ISSUE THREAD

**Issue by RamiKrispin** [Covid19R/covid19R#5]
Hi @aedobbyn @jebyrnes 
If you want me to set for your packages a cron job to refresh the data and push it to the repo please:

- Open an issue and assign it to me, includes the following:
  - A reference for the R script files (or any other language) that run to refresh the data
  - A list of dependencies (e.g., `dplyr`, `devtools`, etc.)
  - Define the refresh intervals (e.g., every 6 hours, etc.)

**Comment by jebyrnes** [comment]
Ah, great, so, does this mean if we need to add a new package, we'll need to define dependencies, etc?

Everything is currently in https://github.com/Covid19R/covid19R_data - and the acquire_data.R script runs the whole thing. Do you want us to file sample issues of adding new packages here so you can update dependencies?

And a 6 hour refresh interval should be fine.

**Comment by RamiKrispin** [comment]
@jebyrnes  the dependencies referred to packages that you are using on the refresh process. Generally, if those packages are already included on the package Imports list on the description file, you should not include them.

**Comment by RamiKrispin** [comment]
And if it is not in a package format, just the list of packages you are using to refresh the data on the script
