### ISSUE TITLE
CanadaC19

### ISSUE THREAD

**Issue by debusklaneml** [Covid19R/covid19R#6]
This issue template is for those of you adding a new data source. Please make sure your package accords to the guidelines set out in https://github.com/Covid19R/documentation. Below, we include a template for us to quickly make sure you are ready to be added. 

Package name: CanadaC19
Dataset names: No local dataset
Package github repo: https://github.com/debusklaneml/CanadaC19/tree/master/data
Data source URL: https://github.com/ishaberry/Covid19Canada/blob/master/cases.csv
License of Data: MIT
URL for Full information about Data Source: https://howsmyflattening.ca/#/data
Do you want this package to be moved to the covid19R organization: Sure
Additional data columns returned beyond the tidy data standard specified in https://github.com/Covid19R/documentation: age, sex, travel_yn, locally_acquired, additional_info, travel_history_country.

- [x] For each dataset, has a `refresh_PKGNAME_*()`function. The _* at the end are for if your package returns multiple datasets.
- [x] Package has a `get_info_PKGNAME()` function.
- [x] Datasets meet the tidy data standard laid out in https://github.com/Covid19R/documentation
- [x] Information returned by `get_info_PKGNAME()` function meets the standards laid out in https://github.com/Covid19R/documentation

Description of data: Imports and cleans data from a repository that includes open-source case data of COVID-19 in Canada. Raw data is available here: <https://github.com/ishaberry/Covid19Canada>.

**Comment by jebyrnes** [comment]
Package is merged into https://github.com/Covid19R/covid19R_data - fantastic - thank you! Add more data sets as you like! Thank you again so much for being our guinea pig!
