### ISSUE TITLE
VirginiaC19

### ISSUE THREAD

**Issue by debusklaneml** [Covid19R/covid19R#7]
Package name: VirginiaC19
Dataset names: 
Package github repo: https://github.com/debusklaneml/VirginiaC19
Data source URL: http://www.vdh.virginia.gov/coronavirus/
License of Data: MIT
URL for Full information about Data Source: http://www.vdh.virginia.gov/coronavirus/
Packages imported: 
Do you want this package to be moved to the covid19R organization: I'll duplicate my repo when approved.
Additional data columns returned beyond the tidy data standard specified in https://github.com/Covid19R/documentation
- vdc_health_district
- hospitalizations

- [x] For each dataset, has a `refresh_PKGNAME_*()`function. The _* at the end are for if your package returns multiple datasets.
- [x] Package has a `get_info_PKGNAME()` function.
- [x] Datasets meet the tidy data standard laid out in https://github.com/Covid19R/documentation
- [x] Information returned by `get_info_PKGNAME()` function meets the standards laid out in https://github.com/Covid19R/documentation

Description of data: Imports and cleans data from Virginia's department
    of health reporting. The original website is here:
    <http://www.vdh.virginia.gov/coronavirus/>.

I'm also working on a 'travis' build:failing issue with this package. For some reason travis does not like my data import and produces a 'cannot open the connection to' error while testing... although devtools::test/check both operate fine in my env.

**Comment by jebyrnes** [comment]
See filed issues in the package - not updating properly. Also, please define these new variables so we can update the standardized vocabulary.

For hospitalizations, please use host_current, hosp_new, or hosp_total. See https://github.com/Covid19R/covid19Rdata/blob/master/controlled_vocabularies/data_type.csv for more.

**Comment by debusklaneml** [comment]
All done. Cheers.

**Comment by jebyrnes** [comment]
FYI - added it to covid19Rdata - should update tonight.
