### ISSUE TITLE
Onboard a new completed covid19tunisia package

### ISSUE THREAD

**Issue by MounaBelaid** [Covid19R/covid19R#9]
Package name: covid19tunisia
Dataset names: data.csv
Package github repo: https://github.com/MounaBelaid/covid19tunisia
Data source URL: https://github.com/MounaBelaid/covid19datatunisia
License of Data: MIT + file LICENSE Copyright (c) 2020 Mouna Belaid
URL for Full information about Data Source: https://github.com/MounaBelaid/covid19datatunisia
Packages imported:  dplyr (>= 0.8.5),
    glue (>= 1.3.2),
    lubridate (>= 1.7.4),
    magrittr (>= 1.5),
    readr (>= 1.3.1),
    stringr (>= 1.4.0),
    tidyr (>= 1.0.2)
Do you want this package to be moved to the covid19R organization: Yes

- [x] For each dataset, has a `refresh_PKGNAME()`function. 
- [x] Package has a `get_info_PKGNAME()` function.
- [x] Datasets meet the tidy data standard laid out in https://github.com/Covid19R/documentation
- [x] Information returned by `get_info_PKGNAME()` function meets the standards laid out in https://github.com/Covid19R/documentation

Description of data:
▲ date - The date in YYYY-MM-DD form.

▲ location - The name of the government as provided by the data sources.

▲ location_type - The type of location using the covid19R controlled vocabulary. In this case, it's “state_government”.

▲ location_code - A standardized location code using a national or international standard. In this case, . See https://www.iso.org/obp/ui/#iso:code:3166:TN for details.

▲ location_code_type The type of standardized location code being used according to the covid19R controlled vocabulary. Here we use “ISO 3166-2:TN”.

▲ data_type - the type of data in that given row. Includes cases new : new confirmed Covid-19 cases during on the current date, recovered_new : new number of patients recovered on the current date and deaths_new : new deaths on the current datea.

▲ value - number of cases of each data type

Other things I'd like to tell you : I have been familiar with working on R since I was at my engineering school. Otherwise, this is the first time that I'm trying to create an R package. So it took me some time to deal with folders in such an open source project and following the template of covid19R project. Therefore, that may be some issues that need to be fixed but most importantly I'm ready to fix anything following your advices and to reach the end by seeing the covid19tunisia package on the CRAN! ✨ 
I have been collected data daily from the official Tunisian sources. I started the work by creating a R Shiny application (https://mounabelaid.shinyapps.io/coronavirus/) that I update daily. I want to explore more this data collected through this great project 💯

**Comment by jebyrnes** [comment]
Very excited! And excited you are using this to learn! Fantastic! I had a problem loading the package - I think you need to rebuild your documentation and rebuild your namespace using devtools (or just the document tab in Rstudio) as right now the namespace is incorrect.

**Comment by MounaBelaid** [comment]
Thank you! I have just fixed the namespace file.

**Comment by jebyrnes** [comment]
Added.
